// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Api.CachuelosSA;

public partial class CachuelosSaContext : DbContext
{
    public CachuelosSaContext()
    {
    }

    public CachuelosSaContext(DbContextOptions<CachuelosSaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Catalogo> Catalogos { get; set; }

    public virtual DbSet<CategoriaTrabajo> CategoriaTrabajos { get; set; }

    public virtual DbSet<ComprobantePago> ComprobantePagos { get; set; }

    public virtual DbSet<Documento> Documentos { get; set; }

    public virtual DbSet<OfertaImagen> OfertaImagens { get; set; }

    public virtual DbSet<OtpAction> OtpActions { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    public virtual DbSet<PagoTrabajador> PagoTrabajadors { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SubastaOfertum> SubastaOferta { get; set; }

    public virtual DbSet<Subastum> Subasta { get; set; }

    public virtual DbSet<TipoDocumento> TipoDocumentos { get; set; }

    public virtual DbSet<Trabajo> Trabajos { get; set; }

    public virtual DbSet<TrabajoImagen> TrabajoImagens { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<UsuarioInfo> UsuarioInfos { get; set; }

    public virtual DbSet<UsuariosXDocumento> UsuariosXDocumentos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-A7VUJ52\\SQLEXPRESS;Initial Catalog=CachuelosSa;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Catalogo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Catalogo__3214EC072E89D73F");

            entity.ToTable("Catalogo", tb => tb.HasTrigger("trg_Catalogo_Update"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Adicional).HasMaxLength(100);
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Descripcion).HasMaxLength(200);
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre).HasMaxLength(100);
            entity.Property(e => e.NombreCat)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<CategoriaTrabajo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC0793D18699");

            entity.ToTable("CategoriaTrabajo", tb => tb.HasTrigger("trg_CategoriaTrabajo_Update"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<ComprobantePago>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comproba__3214EC07EC5C3329");

            entity.ToTable("ComprobantePago");

            entity.Property(e => e.FechaSubida)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UrlComprobante)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Validado).HasDefaultValue(false);

            entity.HasOne(d => d.IdPagoNavigation).WithMany(p => p.ComprobantePagos)
                .HasForeignKey(d => d.IdPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ComprobantePago_Pago");
        });

        modelBuilder.Entity<Documento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Document__3214EC070DEC6C58");

            entity.ToTable("Documento", tb => tb.HasTrigger("trg_Documento_Update"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaIngreso)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UrlDocumento)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.IdTipoDocumentosNavigation).WithMany(p => p.Documentos)
                .HasForeignKey(d => d.IdTipoDocumentos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documento_TipoDocumento");
        });

        modelBuilder.Entity<OfertaImagen>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OfertaIm__3214EC0754F491FB");

            entity.ToTable("OfertaImagen");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaIngreso)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UrlImagen)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.IdOfertaNavigation).WithMany(p => p.OfertaImagens)
                .HasForeignKey(d => d.IdOferta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfertaImagen_Oferta");
        });

        modelBuilder.Entity<OtpAction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OtpActio__3214EC078A734A69");

            entity.ToTable("OtpAction", tb => tb.HasTrigger("trg_OtpAction_Update"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CodigoOtp)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Expiracion).HasColumnType("datetime");
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaGeneracion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TipoOtp)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.Usado).HasDefaultValue(false);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.OtpActions)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_OtpAction");
        });

        modelBuilder.Entity<Pago>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pago__3214EC075E4C08F5");

            entity.ToTable("Pago");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.EstadoPago).HasMaxLength(20);
            entity.Property(e => e.FechaPago)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MetodoPago).HasMaxLength(50);
            entity.Property(e => e.Monto).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdTrabajoNavigation).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.IdTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pago_Trabajo");
        });

        modelBuilder.Entity<PagoTrabajador>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PagoTrab__3214EC07FCA7550D");

            entity.ToTable("PagoTrabajador");

            entity.Property(e => e.Estado).HasMaxLength(20);
            entity.Property(e => e.FechaTransferencia).HasColumnType("datetime");
            entity.Property(e => e.Monto).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdPagoNavigation).WithMany(p => p.PagoTrabajadors)
                .HasForeignKey(d => d.IdPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PagoTrabajador_Pago");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC0790A61A19");

            entity.HasIndex(e => e.NombreRol, "UQ__Roles__4F0B537F20025383").IsUnique();

            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.NombreRol)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SubastaOfertum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SubastaO__3214EC07F75F6656");

            entity.Property(e => e.FechaOferta)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Mensaje).HasMaxLength(500);
            entity.Property(e => e.Monto).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdSubastaNavigation).WithMany(p => p.SubastaOferta)
                .HasForeignKey(d => d.IdSubasta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Oferta_Subasta");

            entity.HasOne(d => d.IdUsuarioTrabajadorNavigation).WithMany(p => p.SubastaOferta)
                .HasForeignKey(d => d.IdUsuarioTrabajador)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Oferta_Usuario");
        });

        modelBuilder.Entity<Subastum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Subasta__3214EC0700DD20AC");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.FechaFin).HasColumnType("datetime");
            entity.Property(e => e.FechaInicio)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.IdTrabajoNavigation).WithMany(p => p.Subasta)
                .HasForeignKey(d => d.IdTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Subasta_Trabajo");
        });

        modelBuilder.Entity<TipoDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoDocu__3214EC073330D35D");

            entity.HasIndex(e => e.NombreDocumento, "UQ__TipoDocu__637890AB91BDF8A7").IsUnique();

            entity.Property(e => e.Descripcion).HasMaxLength(255);
            entity.Property(e => e.NombreDocumento)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Trabajo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Trabajo__3214EC07E2E646B1");

            entity.ToTable("Trabajo");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Direccion).HasMaxLength(255);
            entity.Property(e => e.Especial).HasDefaultValue(false);
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaFinSubasta).HasColumnType("datetime");
            entity.Property(e => e.FechaPublicacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaTrabajo).HasColumnType("datetime");
            entity.Property(e => e.Latitud).HasColumnType("decimal(10, 7)");
            entity.Property(e => e.Longitud).HasColumnType("decimal(10, 7)");
            entity.Property(e => e.PrecioReferencial).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.IdCategoriaNavigation).WithMany(p => p.Trabajos)
                .HasForeignKey(d => d.IdCategoria)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trabajo_Categoria");

            entity.HasOne(d => d.IdUsuarioCreadorNavigation).WithMany(p => p.TrabajoIdUsuarioCreadorNavigations)
                .HasForeignKey(d => d.IdUsuarioCreador)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trabajo_Usuario");

            entity.HasOne(d => d.IdUsuarioTrabajadorAsignadoNavigation).WithMany(p => p.TrabajoIdUsuarioTrabajadorAsignadoNavigations)
                .HasForeignKey(d => d.IdUsuarioTrabajadorAsignado)
                .HasConstraintName("FK_Trabajo_UsuarioTrabajadorAsignado");
        });

        modelBuilder.Entity<TrabajoImagen>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TrabajoI__3214EC076769A87A");

            entity.ToTable("TrabajoImagen");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaIngreso)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UrlImagen)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.IdTrabajoNavigation).WithMany(p => p.TrabajoImagens)
                .HasForeignKey(d => d.IdTrabajo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TrabajoImagen_Trabajo");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC0767A3BFB0");

            entity.ToTable(tb => tb.HasTrigger("trg_Usuarios_Update"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.ContrasenaHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ExpiracionToken).HasColumnType("datetime");
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaFinSubscrito).HasColumnType("datetime");
            entity.Property(e => e.FechaUltimoLogin).HasColumnType("datetime");
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RolId).HasDefaultValue(1);
            entity.Property(e => e.Subscrito).HasDefaultValue(false);
            entity.Property(e => e.TokenRecuperacion).HasMaxLength(255);
            entity.Property(e => e.Verificado).HasDefaultValue(false);

            entity.HasOne(d => d.Rol).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.RolId)
                .HasConstraintName("FK_Usuarios_Roles");
        });

        modelBuilder.Entity<UsuarioInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UsuarioI__3214EC079DB28AC3");

            entity.ToTable("UsuarioInfo", tb => tb.HasTrigger("trg_UsuariosInfo_Update"));

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Apellido).HasMaxLength(200);
            entity.Property(e => e.Ciudad).HasMaxLength(5);
            entity.Property(e => e.Direccion).HasMaxLength(255);
            entity.Property(e => e.Discapacidad).HasDefaultValue(false);
            entity.Property(e => e.EstadoCivil).HasMaxLength(1);
            entity.Property(e => e.FechaActualizacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaNacimiento)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaUltimaConexion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Identificacion).HasMaxLength(50);
            entity.Property(e => e.Nacionalidad).HasMaxLength(5);
            entity.Property(e => e.Nombre).HasMaxLength(200);
            entity.Property(e => e.Provincia).HasMaxLength(5);
            entity.Property(e => e.Telefono).HasMaxLength(20);
            entity.Property(e => e.TipoDiscapacidad).HasMaxLength(100);
            entity.Property(e => e.TipoIdentificacion).HasMaxLength(1);
            entity.Property(e => e.UrlImg).HasMaxLength(500);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioInfos)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_UsuarioInfo");
        });

        modelBuilder.Entity<UsuariosXDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC07058BAE5C");

            entity.Property(e => e.FechaAsignacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.IdDocumentoNavigation).WithMany(p => p.UsuariosXDocumentos)
                .HasForeignKey(d => d.IdDocumento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuariosXDocumentos_Documento");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuariosXDocumentos)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuariosXDocumentos_Usuarios");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}