// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class ComprobantePago
{
    public int Id { get; set; }

    public int IdPago { get; set; }

    public string UrlComprobante { get; set; }

    public DateTime? FechaSubida { get; set; }

    public bool? Validado { get; set; }

    public virtual Pago IdPagoNavigation { get; set; }
}