// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class PagoTrabajador
{
    public int Id { get; set; }

    public int IdPago { get; set; }

    public int IdUsuarioTrabajador { get; set; }

    public decimal Monto { get; set; }

    public DateTime? FechaTransferencia { get; set; }

    public string Estado { get; set; }

    public virtual Pago IdPagoNavigation { get; set; }
}