// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class Pago
{
    public int Id { get; set; }

    public int IdTrabajo { get; set; }

    public int IdUsuarioPagador { get; set; }

    public decimal Monto { get; set; }

    public string MetodoPago { get; set; }

    public string EstadoPago { get; set; }

    public DateTime? FechaPago { get; set; }

    public bool? Activo { get; set; }

    public virtual ICollection<ComprobantePago> ComprobantePagos { get; set; } = new List<ComprobantePago>();

    public virtual Trabajo IdTrabajoNavigation { get; set; }

    public virtual ICollection<PagoTrabajador> PagoTrabajadors { get; set; } = new List<PagoTrabajador>();
}