// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class SubastaOfertum
{
    public int Id { get; set; }

    public int IdSubasta { get; set; }

    public int IdUsuarioTrabajador { get; set; }

    public decimal Monto { get; set; }

    public string Mensaje { get; set; }

    public DateTime? FechaOferta { get; set; }

    public virtual Subastum IdSubastaNavigation { get; set; }

    public virtual Usuario IdUsuarioTrabajadorNavigation { get; set; }

    public virtual ICollection<OfertaImagen> OfertaImagens { get; set; } = new List<OfertaImagen>();
}