// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class TrabajoImagen
{
    public int Id { get; set; }

    public int IdTrabajo { get; set; }

    public string UrlImagen { get; set; }

    public DateTime? FechaIngreso { get; set; }

    public bool? Activo { get; set; }

    public virtual Trabajo IdTrabajoNavigation { get; set; }
}