// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class UsuarioInfo
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string UrlImg { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaUltimaConexion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}