// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.CachuelosSA;

public partial class Usuario
{
    public int Id { get; set; }

    public string NombreUsuario { get; set; }

    public string Correo { get; set; }

    public string ContrasenaHash { get; set; }

    public bool? Verificado { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaUltimoLogin { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public string Rol { get; set; }

    public string TokenRecuperacion { get; set; }

    public DateTime? ExpiracionToken { get; set; }
}