// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class Documento
{
    public int Id { get; set; }

    public string UrlDocumento { get; set; }

    public int IdTipoDocumentos { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaIngreso { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual TipoDocumento IdTipoDocumentosNavigation { get; set; }

    public virtual ICollection<UsuariosXDocumento> UsuariosXDocumentos { get; set; } = new List<UsuariosXDocumento>();
}