// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class OtpAction
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string CodigoOtp { get; set; }

    public string TipoOtp { get; set; }

    public DateTime Expiracion { get; set; }

    public bool? Usado { get; set; }

    public DateTime? FechaGeneracion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool? Activo { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}