// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class Role
{
    public int Id { get; set; }

    public string NombreRol { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}