// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class Subastum
{
    public int Id { get; set; }

    public int IdTrabajo { get; set; }

    public string Estado { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public virtual Trabajo IdTrabajoNavigation { get; set; }

    public virtual ICollection<SubastaOfertum> SubastaOferta { get; set; } = new List<SubastaOfertum>();
}