// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class TipoDocumento
{
    public int Id { get; set; }

    public string NombreDocumento { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();
}