// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class Trabajo
{
    public int Id { get; set; }

    public int IdUsuarioCreador { get; set; }

    public int IdCategoria { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string Direccion { get; set; }

    public decimal? Latitud { get; set; }

    public decimal? Longitud { get; set; }

    public decimal? PrecioReferencial { get; set; }

    public bool? Especial { get; set; }

    public string Estado { get; set; }

    public DateTime? FechaPublicacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaFinSubasta { get; set; }

    public DateTime? FechaTrabajo { get; set; }

    public int? TiempoEstimadoTrabajo { get; set; }

    public int? IdUsuarioTrabajadorAsignado { get; set; }

    public virtual CategoriaTrabajo IdCategoriaNavigation { get; set; }

    public virtual Usuario IdUsuarioCreadorNavigation { get; set; }

    public virtual Usuario IdUsuarioTrabajadorAsignadoNavigation { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();

    public virtual ICollection<Subastum> Subasta { get; set; } = new List<Subastum>();

    public virtual ICollection<TrabajoImagen> TrabajoImagens { get; set; } = new List<TrabajoImagen>();
}