// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class UsuariosXDocumento
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public int IdDocumento { get; set; }

    public DateTime? FechaAsignacion { get; set; }

    public virtual Documento IdDocumentoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}