// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entitys.CachuelosSA;

public partial class UsuarioInfo
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string TipoIdentificacion { get; set; }

    public string Identificacion { get; set; }

    public string EstadoCivil { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }

    public string Nacionalidad { get; set; }

    public bool? Discapacidad { get; set; }

    public string TipoDiscapacidad { get; set; }

    public string UrlImg { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaUltimaConexion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}