INSERT INTO Catalogo (NombreCat, Codigo, Nombre, Adicional, Descripcion)
values 
('NACIONALIDADES', 'AW', 'aruba', '', ''),
('NACIONALIDADES', 'AF', 'afghanistan', '', ''),
('NACIONALIDADES', 'AO', 'angola', '', ''),
('NACIONALIDADES', 'AI', 'anguilla', '', ''),
('NACIONALIDADES', 'AX', 'åland islands', '', ''),
('NACIONALIDADES', 'AL', 'albania', '', ''),
('NACIONALIDADES', 'AD', 'andorra', '', ''),
('NACIONALIDADES', 'AE', 'united arab emirates', '', ''),
('NACIONALIDADES', 'AR', 'argentina', '', ''),
('NACIONALIDADES', 'AM', 'armenia', '', ''),
('NACIONALIDADES', 'AS', 'american samoa', '', ''),
('NACIONALIDADES', 'AQ', 'antarctica', '', ''),
('NACIONALIDADES', 'TF', 'french southern territories', '', ''),
('NACIONALIDADES', 'AG', 'antigua and barbuda', '', ''),
('NACIONALIDADES', 'AU', 'australia', '', ''),
('NACIONALIDADES', 'AT', 'austria', '', ''),
('NACIONALIDADES', 'AZ', 'azerbaijan', '', ''),
('NACIONALIDADES', 'BI', 'burundi', '', ''),
('NACIONALIDADES', 'BE', 'belgium', '', ''),
('NACIONALIDADES', 'BJ', 'benin', '', ''),
('NACIONALIDADES', 'BQ', 'bonaire, sint eustatius and saba', '', ''),
('NACIONALIDADES', 'BF', 'burkina faso', '', ''),
('NACIONALIDADES', 'BD', 'bangladesh', '', ''),
('NACIONALIDADES', 'BG', 'bulgaria', '', ''),
('NACIONALIDADES', 'BH', 'bahrain', '', ''),
('NACIONALIDADES', 'BS', 'bahamas', '', ''),
('NACIONALIDADES', 'BA', 'bosnia and herzegovina', '', ''),
('NACIONALIDADES', 'BL', 'saint barthélemy', '', ''),
('NACIONALIDADES', 'BY', 'belarus', '', ''),
('NACIONALIDADES', 'BZ', 'belize', '', ''),
('NACIONALIDADES', 'BM', 'bermuda', '', ''),
('NACIONALIDADES', 'BO', 'bolivia', '', ''),
('NACIONALIDADES', 'BR', 'brazil', '', ''),
('NACIONALIDADES', 'BB', 'barbados', '', ''),
('NACIONALIDADES', 'BN', 'brunei darussalam', '', ''),
('NACIONALIDADES', 'BT', 'bhutan', '', ''),
('NACIONALIDADES', 'BV', 'bouvet island', '', ''),
('NACIONALIDADES', 'BW', 'botswana', '', ''),
('NACIONALIDADES', 'CF', 'central african republic', '', ''),
('NACIONALIDADES', 'CA', 'canada', '', ''),
('NACIONALIDADES', 'CC', 'cocos (keeling) islands', '', ''),
('NACIONALIDADES', 'CH', 'switzerland', '', ''),
('NACIONALIDADES', 'CL', 'chile', '', ''),
('NACIONALIDADES', 'CN', 'china', '', ''),
('NACIONALIDADES', 'CI', 'côte divoire', '', ''),
('NACIONALIDADES', 'CM', 'cameroon', '', ''),
('NACIONALIDADES', 'CD', 'congo, the democratic republic of the', '', ''),
('NACIONALIDADES', 'CG', 'congo', '', ''),
('NACIONALIDADES', 'CK', 'cook islands', '', ''),
('NACIONALIDADES', 'CO', 'colombia', '', ''),
('NACIONALIDADES', 'KM', 'comoros', '', ''),
('NACIONALIDADES', 'CV', 'cabo verde', '', ''),
('NACIONALIDADES', 'CR', 'costa rica', '', ''),
('NACIONALIDADES', 'CU', 'cuba', '', ''),
('NACIONALIDADES', 'CW', 'curaçao', '', ''),
('NACIONALIDADES', 'CX', 'christmas island', '', ''),
('NACIONALIDADES', 'KY', 'cayman islands', '', ''),
('NACIONALIDADES', 'CY', 'cyprus', '', ''),
('NACIONALIDADES', 'CZ', 'czechia', '', ''),
('NACIONALIDADES', 'DE', 'germany', '', ''),
('NACIONALIDADES', 'DJ', 'djibouti', '', ''),
('NACIONALIDADES', 'DM', 'dominica', '', ''),
('NACIONALIDADES', 'DK', 'denmark', '', ''),
('NACIONALIDADES', 'DO', 'dominican republic', '', ''),
('NACIONALIDADES', 'DZ', 'algeria', '', ''),
('NACIONALIDADES', 'EC', 'ecuador', '', ''),
('NACIONALIDADES', 'EG', 'egypt', '', ''),
('NACIONALIDADES', 'ER', 'eritrea', '', ''),
('NACIONALIDADES', 'EH', 'western sahara', '', ''),
('NACIONALIDADES', 'ES', 'spain', '', ''),
('NACIONALIDADES', 'EE', 'estonia', '', ''),
('NACIONALIDADES', 'ET', 'ethiopia', '', ''),
('NACIONALIDADES', 'FI', 'finland', '', ''),
('NACIONALIDADES', 'FJ', 'fiji', '', ''),
('NACIONALIDADES', 'FK', 'falkland islands (malvinas)', '', ''),
('NACIONALIDADES', 'FR', 'france', '', ''),
('NACIONALIDADES', 'FO', 'faroe islands', '', ''),
('NACIONALIDADES', 'FM', 'federated states of micronesia', '', ''),
('NACIONALIDADES', 'GA', 'gabon', '', ''),
('NACIONALIDADES', 'GB', 'united kingdom', '', ''),
('NACIONALIDADES', 'GE', 'georgia', '', ''),
('NACIONALIDADES', 'GG', 'guernsey', '', ''),
('NACIONALIDADES', 'GH', 'ghana', '', ''),
('NACIONALIDADES', 'GI', 'gibraltar', '', ''),
('NACIONALIDADES', 'GN', 'guinea', '', ''),
('NACIONALIDADES', 'GP', 'guadeloupe', '', ''),
('NACIONALIDADES', 'GM', 'gambia', '', ''),
('NACIONALIDADES', 'GW', 'guinea-bissau', '', ''),
('NACIONALIDADES', 'GQ', 'equatorial guinea', '', ''),
('NACIONALIDADES', 'GR', 'greece', '', ''),
('NACIONALIDADES', 'GD', 'grenada', '', ''),
('NACIONALIDADES', 'GL', 'greenland', '', ''),
('NACIONALIDADES', 'GT', 'guatemala', '', ''),
('NACIONALIDADES', 'GF', 'french guiana', '', ''),
('NACIONALIDADES', 'GU', 'guam', '', ''),
('NACIONALIDADES', 'GY', 'guyana', '', ''),
('NACIONALIDADES', 'HK', 'hong kong', '', ''),
('NACIONALIDADES', 'HM', 'heard island and mcdonald islands', '', ''),
('NACIONALIDADES', 'HN', 'honduras', '', ''),
('NACIONALIDADES', 'HR', 'croatia', '', ''),
('NACIONALIDADES', 'HT', 'haiti', '', ''),
('NACIONALIDADES', 'HU', 'hungary', '', ''),
('NACIONALIDADES', 'ID', 'indonesia', '', ''),
('NACIONALIDADES', 'IM', 'isle of man', '', ''),
('NACIONALIDADES', 'IN', 'india', '', ''),
('NACIONALIDADES', 'IO', 'british indian ocean territory', '', ''),
('NACIONALIDADES', 'IE', 'ireland', '', ''),
('NACIONALIDADES', 'IR', 'iran', '', ''),
('NACIONALIDADES', 'IQ', 'iraq', '', ''),
('NACIONALIDADES', 'IS', 'iceland', '', ''),
('NACIONALIDADES', 'IL', 'israel', '', ''),
('NACIONALIDADES', 'IT', 'italy', '', ''),
('NACIONALIDADES', 'JM', 'jamaica', '', ''),
('NACIONALIDADES', 'JE', 'jersey', '', ''),
('NACIONALIDADES', 'JO', 'jordan', '', ''),
('NACIONALIDADES', 'JP', 'japan', '', ''),
('NACIONALIDADES', 'KZ', 'kazakhstan', '', ''),
('NACIONALIDADES', 'KE', 'kenya', '', ''),
('NACIONALIDADES', 'KG', 'kyrgyzstan', '', ''),
('NACIONALIDADES', 'KH', 'cambodia', '', ''),
('NACIONALIDADES', 'KI', 'kiribati', '', ''),
('NACIONALIDADES', 'KN', 'saint kitts and nevis', '', ''),
('NACIONALIDADES', 'KR', 'korea', '', ''),
('NACIONALIDADES', 'KW', 'kuwait', '', ''),
('NACIONALIDADES', 'LA', 'lao peoples democratic republic', '', ''),
('NACIONALIDADES', 'LB', 'lebanon', '', ''),
('NACIONALIDADES', 'LR', 'liberia', '', ''),
('NACIONALIDADES', 'LY', 'libya', '', ''),
('NACIONALIDADES', 'LC', 'saint lucia', '', ''),
('NACIONALIDADES', 'LI', 'liechtenstein', '', ''),
('NACIONALIDADES', 'LK', 'sri lanka', '', ''),
('NACIONALIDADES', 'LS', 'lesotho', '', ''),
('NACIONALIDADES', 'LT', 'lithuania', '', ''),
('NACIONALIDADES', 'LU', 'luxembourg', '', ''),
('NACIONALIDADES', 'LV', 'latvia', '', ''),
('NACIONALIDADES', 'MO', 'macao', '', ''),
('NACIONALIDADES', 'MF', 'saint martin (french part)', '', ''),
('NACIONALIDADES', 'MA', 'morocco', '', ''),
('NACIONALIDADES', 'MC', 'monaco', '', ''),
('NACIONALIDADES', 'MD', 'moldova', '', ''),
('NACIONALIDADES', 'MG', 'madagascar', '', ''),
('NACIONALIDADES', 'MV', 'maldives', '', ''),
('NACIONALIDADES', 'MX', 'mexico', '', ''),
('NACIONALIDADES', 'MH', 'marshall islands', '', ''),
('NACIONALIDADES', 'MK', 'north macedonia', '', ''),
('NACIONALIDADES', 'ML', 'mali', '', ''),
('NACIONALIDADES', 'MT', 'malta', '', ''),
('NACIONALIDADES', 'MM', 'myanmar', '', ''),
('NACIONALIDADES', 'ME', 'montenegro', '', ''),
('NACIONALIDADES', 'MN', 'mongolia', '', ''),
('NACIONALIDADES', 'MP', 'northern mariana islands', '', ''),
('NACIONALIDADES', 'MZ', 'mozambique', '', ''),
('NACIONALIDADES', 'MR', 'mauritania', '', ''),
('NACIONALIDADES', 'MS', 'montserrat', '', ''),
('NACIONALIDADES', 'MQ', 'martinique', '', ''),
('NACIONALIDADES', 'MU', 'mauritius', '', ''),
('NACIONALIDADES', 'MW', 'malawi', '', ''),
('NACIONALIDADES', 'MY', 'malaysia', '', ''),
('NACIONALIDADES', 'YT', 'mayotte', '', ''),
('NACIONALIDADES', 'NA', 'namibia', '', ''),
('NACIONALIDADES', 'NC', 'new caledonia', '', ''),
('NACIONALIDADES', 'NE', 'niger', '', ''),
('NACIONALIDADES', 'NF', 'norfolk island', '', ''),
('NACIONALIDADES', 'NG', 'nigeria', '', ''),
('NACIONALIDADES', 'NI', 'nicaragua', '', ''),
('NACIONALIDADES', 'NU', 'niue', '', ''),
('NACIONALIDADES', 'NL', 'netherlands', '', ''),
('NACIONALIDADES', 'NO', 'norway', '', ''),
('NACIONALIDADES', 'NP', 'nepal', '', ''),
('NACIONALIDADES', 'NR', 'nauru', '', ''),
('NACIONALIDADES', 'NZ', 'new zealand', '', ''),
('NACIONALIDADES', 'OM', 'oman', '', ''),
('NACIONALIDADES', 'PK', 'pakistan', '', ''),
('NACIONALIDADES', 'PA', 'panama', '', ''),
('NACIONALIDADES', 'PN', 'pitcairn', '', ''),
('NACIONALIDADES', 'PE', 'peru', '', ''),
('NACIONALIDADES', 'PH', 'philippines', '', ''),
('NACIONALIDADES', 'PW', 'palau', '', ''),
('NACIONALIDADES', 'PG', 'papua new guinea', '', ''),
('NACIONALIDADES', 'PL', 'poland', '', ''),
('NACIONALIDADES', 'PR', 'puerto rico', '', ''),
('NACIONALIDADES', 'KP', 'korea', '', ''),
('NACIONALIDADES', 'PT', 'portugal', '', ''),
('NACIONALIDADES', 'PY', 'paraguay', '', ''),
('NACIONALIDADES', 'PS', 'palestine', '', ''),
('NACIONALIDADES', 'PF', 'french polynesia', '', ''),
('NACIONALIDADES', 'QA', 'qatar', '', ''),
('NACIONALIDADES', 'RE', 'réunion', '', ''),
('NACIONALIDADES', 'RO', 'romania', '', ''),
('NACIONALIDADES', 'RU', 'russian federation', '', ''),
('NACIONALIDADES', 'RW', 'rwanda', '', ''),
('NACIONALIDADES', 'SA', 'saudi arabia', '', ''),
('NACIONALIDADES', 'SD', 'sudan', '', ''),
('NACIONALIDADES', 'SN', 'senegal', '', ''),
('NACIONALIDADES', 'SG', 'singapore', '', ''),
('NACIONALIDADES', 'GS', 'south georgia and the south sandwich islands', '', ''),
('NACIONALIDADES', 'SH', 'saint helena, ascension and tristan da cunha', '', ''),
('NACIONALIDADES', 'SJ', 'svalbard and jan mayen', '', ''),
('NACIONALIDADES', 'SB', 'solomon islands', '', ''),
('NACIONALIDADES', 'SL', 'sierra leone', '', ''),
('NACIONALIDADES', 'SV', 'el salvador', '', ''),
('NACIONALIDADES', 'SM', 'san marino', '', ''),
('NACIONALIDADES', 'SO', 'somalia', '', ''),
('NACIONALIDADES', 'PM', 'saint pierre and miquelon', '', ''),
('NACIONALIDADES', 'RS', 'serbia', '', ''),
('NACIONALIDADES', 'SS', 'south sudan', '', ''),
('NACIONALIDADES', 'ST', 'sao tome and principe', '', ''),
('NACIONALIDADES', 'SR', 'suriname', '', ''),
('NACIONALIDADES', 'SK', 'slovakia', '', ''),
('NACIONALIDADES', 'SI', 'slovenia', '', ''),
('NACIONALIDADES', 'SE', 'sweden', '', ''),
('NACIONALIDADES', 'SZ', 'eswatini', '', ''),
('NACIONALIDADES', 'SX', 'sint maarten (dutch part)', '', ''),
('NACIONALIDADES', 'SC', 'seychelles', '', ''),
('NACIONALIDADES', 'SY', 'syrian arab republic', '', ''),
('NACIONALIDADES', 'TC', 'turks and caicos islands', '', ''),
('NACIONALIDADES', 'TD', 'chad', '', ''),
('NACIONALIDADES', 'TG', 'togo', '', ''),
('NACIONALIDADES', 'TH', 'thailand', '', ''),
('NACIONALIDADES', 'TJ', 'tajikistan', '', ''),
('NACIONALIDADES', 'TK', 'tokelau', '', ''),
('NACIONALIDADES', 'TM', 'turkmenistan', '', ''),
('NACIONALIDADES', 'TL', 'timor-leste', '', ''),
('NACIONALIDADES', 'TO', 'tonga', '', ''),
('NACIONALIDADES', 'TT', 'trinidad and tobago', '', ''),
('NACIONALIDADES', 'TN', 'tunisia', '', ''),
('NACIONALIDADES', 'TR', 'turkey', '', ''),
('NACIONALIDADES', 'TV', 'tuvalu', '', ''),
('NACIONALIDADES', 'TW', 'taiwan', '', ''),
('NACIONALIDADES', 'TZ', 'tanzania', '', ''),
('NACIONALIDADES', 'UG', 'uganda', '', ''),
('NACIONALIDADES', 'UA', 'ukraine', '', ''),
('NACIONALIDADES', 'UM', 'united states minor outlying islands', '', ''),
('NACIONALIDADES', 'UY', 'uruguay', '', ''),
('NACIONALIDADES', 'US', 'united states', '', ''),
('NACIONALIDADES', 'UZ', 'uzbekistan', '', ''),
('NACIONALIDADES', 'VA', 'holy see (vatican city state)', '', ''),
('NACIONALIDADES', 'VC', 'saint vincent and the grenadines', '', ''),
('NACIONALIDADES', 'VE', 'venezuela', '', ''),
('NACIONALIDADES', 'VG', 'virgin islands, british', '', ''),
('NACIONALIDADES', 'VI', 'virgin islands, u.s.', '', ''),
('NACIONALIDADES', 'VN', 'viet nam', '', ''),
('NACIONALIDADES', 'VU', 'vanuatu', '', ''),
('NACIONALIDADES', 'WF', 'wallis and futuna', '', ''),
('NACIONALIDADES', 'WS', 'samoa', '', ''),
('NACIONALIDADES', 'YE', 'yemen', '', ''),
('NACIONALIDADES', 'ZA', 'south africa', '', ''),
('NACIONALIDADES', 'ZM', 'zambia', '', ''),
('NACIONALIDADES', 'ZW', 'zimbabwe', '', ''),
('PROVINCIAS', 'AZU', 'Azuay', 'EC', ''),
('PROVINCIAS', 'BOL', 'Bolívar', 'EC', ''),
('PROVINCIAS', 'CAR', 'Carchi', 'EC', ''),
('PROVINCIAS', 'CAÑ', 'Cañar', 'EC', ''),
('PROVINCIAS', 'CHI', 'Chimborazo', 'EC', ''),
('PROVINCIAS', 'COT', 'Cotopaxi', 'EC', ''),
('PROVINCIAS', 'EL ', 'El Oro', 'EC', ''),
('PROVINCIAS', 'ESM', 'Esmeraldas', 'EC', ''),
('PROVINCIAS', 'GAL', 'Galápagos', 'EC', ''),
('PROVINCIAS', 'GUA', 'Guayas', 'EC', ''),
('PROVINCIAS', 'IMB', 'Imbabura', 'EC', ''),
('PROVINCIAS', 'LOJ', 'Loja', 'EC', ''),
('PROVINCIAS', 'LOS', 'Los Ríos', 'EC', ''),
('PROVINCIAS', 'MAN', 'Manabí', 'EC', ''),
('PROVINCIAS', 'MOR', 'Morona Santiago', 'EC', ''),
('PROVINCIAS', 'NAP', 'Napo', 'EC', ''),
('PROVINCIAS', 'ORE', 'Orellana', 'EC', ''),
('PROVINCIAS', 'PAS', 'Pastaza', 'EC', ''),
('PROVINCIAS', 'PIC', 'Pichincha', 'EC', ''),
('PROVINCIAS', 'SAN', 'Santa Elena', 'EC', ''),
('PROVINCIAS', 'SAN', 'Santo Domingo De Los Tsáchilas', 'EC', ''),
('PROVINCIAS', 'SUC', 'Sucumbíos', 'EC', ''),
('PROVINCIAS', 'TUN', 'Tungurahua', 'EC', ''),
('PROVINCIAS', 'ZAM', 'Zamora Chinchipe', 'EC', ''),
('CIUDADES', 'CUE', 'Cuenca', 'CUE', ''),
('CIUDADES', 'GUA', 'Gualaceo', 'GUA', ''),
('CIUDADES', 'PAU', 'Paute', 'PAU', ''),
('CIUDADES', 'GIR', 'Girón', 'GIR', ''),
('CIUDADES', 'GUA', 'Guaranda', 'GUA', ''),
('CIUDADES', 'AZO', 'Azogues', 'AZO', ''),
('CIUDADES', 'LA ', 'La Troncal', 'LA ', ''),
('CIUDADES', 'TUL', 'Tulcán', 'TUL', ''),
('CIUDADES', 'RIO', 'Riobamba', 'RIO', ''),
('CIUDADES', 'GUA', 'Guano', 'GUA', ''),
('CIUDADES', 'LAT', 'Latacunga', 'LAT', ''),
('CIUDADES', 'SAL', 'Salcedo', 'SAL', ''),
('CIUDADES', 'MAC', 'Machala', 'MAC', ''),
('CIUDADES', 'SAN', 'Santa Rosa', 'SAN', ''),
('CIUDADES', 'ESM', 'Esmeraldas', 'ESM', ''),
('CIUDADES', 'PUE', 'Puerto Ayora', 'PUE', ''),
('CIUDADES', 'GUA', 'Guayaquil', 'GUA', ''),
('CIUDADES', 'SAM', 'Samborondón', 'SAM', ''),
('CIUDADES', 'DAU', 'Daule', 'DAU', ''),
('CIUDADES', 'MIL', 'Milagro', 'MIL', ''),
('CIUDADES', 'IBA', 'Ibarra', 'IBA', ''),
('CIUDADES', 'OTA', 'Otavalo', 'OTA', ''),
('CIUDADES', 'LOJ', 'Loja', 'LOJ', ''),
('CIUDADES', 'BAB', 'Babahoyo', 'BAB', ''),
('CIUDADES', 'QUE', 'Quevedo', 'QUE', ''),
('CIUDADES', 'POR', 'Portoviejo', 'POR', ''),
('CIUDADES', 'MAN', 'Manta', 'MAN', ''),
('CIUDADES', 'MAC', 'Macas', 'MAC', ''),
('CIUDADES', 'TEN', 'Tena', 'TEN', ''),
('CIUDADES', 'FRA', 'Francisco de Orellana', 'FRA', ''),
('CIUDADES', 'PUY', 'Puyo', 'PUY', ''),
('CIUDADES', 'QUI', 'Quito', 'QUI', ''),
('CIUDADES', 'CAY', 'Cayambe', 'CAY', ''),
('CIUDADES', 'RUM', 'Rumiñahui', 'RUM', ''),
('CIUDADES', 'SAN', 'Santa Elena', 'SAN', ''),
('CIUDADES', 'SAN', 'Santo Domingo', 'SAN', ''),
('CIUDADES', 'NUE', 'Nueva Loja', 'NUE', ''),
('CIUDADES', 'AMB', 'Ambato', 'AMB', ''),
('CIUDADES', 'ZAM', 'Zamora', 'ZAM', '');